version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  simple:
    format: "%(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  Bert_Cleaner:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Bert_Cleaner.log
    encoding: utf8
    mode : w

  Bert_Cleaner_Functions:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Bert_Cleaner_Functions.log
    encoding: utf8 
    mode : w

  Bert_Datasplit:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Bert_Datasplit.log
    encoding: utf8
    mode : w

  Paraphraser:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Paraphraser.log
    encoding: utf8
    mode : w

  Bert_Semantic:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Bert_Semantic.log
    encoding: utf8
    mode : w

  Compare:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Compare.log
    encoding: utf8
    mode : w

  Flask:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Flask.log
    encoding: utf8
    mode : w
  
  Extract:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Extract.log
    encoding: utf8
    mode : w

  Optuna:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Optuna.log
    encoding: utf8
    mode : w
  
  Scraper:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: Logs/Scraper.log
    encoding: utf8
    mode : w

loggers:
  Bert_Cleaner:
    level: DEBUG
    handlers: [Bert_Cleaner]
    propagate: no

  Bert_Cleaner_Functions:
    level: DEBUG
    handlers: [Bert_Cleaner_Functions]
    propagate: no

  Paraphraser:
    level: DEBUG
    handlers: [Paraphraser]
    propagate: no
  
  Bert_Datasplit:
    level: DEBUG
    handlers: [Bert_Datasplit]
    propagate: no

  Bert_Semantic:
    level: DEBUG
    handlers: [Bert_Semantic]
    propagate: no

  Compare:
    level: DEBUG
    handlers: [Compare]
    propagate: no

  Flask:
    level: DEBUG
    handlers: [Flask]
    propagate: no

  Extract:
    level: DEBUG
    handlers: [Extract]
    propagate: no

  Optuna:
    level: DEBUG
    handlers: [Optuna]
    propagate: no

  Scraper:
    level: DEBUG
    handlers: [Scraper]
    propagate: no

root:
  level: WARNING
  handlers: [console]